MvcApplication/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business.DomainModel;
using Business.Repository;
using Business.Service;

using AutoMapper;

namespace MvcApplication.Controllers
{
    public class RestaurantController : Controller
    {
        private IMappingEngine _mappingEngine;
        private IRestaurantRepository _restaurantRepository;
        private IRestaurantService _restaurantService;

        public RestaurantController(IMappingEngine mappingEngine,
            IRestaurantRepository restaurantRepository,
            IRestaurantService restaurantService)
        {
            _mappingEngine = mappingEngine;
            _restaurantRepository = restaurantRepository;
            _restaurantService = restaurantService;
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var restaurant = _restaurantRepository.Get(id);

            if (restaurant == null) // restaurant not found
                return RedirectToAction("Index", "Home");

            return View(_mappingEngine.Map<Models.RestaurantModel>(restaurant));
        }

        [HttpGet]
        public ActionResult Photo(int id)
        {
            var restaurant = _restaurantRepository.Get(id);

            var data = new byte[0];
            if (restaurant != null && restaurant.Photo != null)
            {
                data = restaurant.Photo;
            }
            return File(data, "image/jpeg");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Models.RestaurantModel restaurantVm)
        {
            if (ModelState.IsValid)
            {
                // validate file and it's size
                if (restaurantVm.Photo != null)
                {
                    if (!restaurantVm.Photo.ContentType.Equals("image/jpeg", StringComparison.InvariantCultureIgnoreCase))
                    {
                        ViewBag.ErrorMessage = "Only JPEG photos are supported, please upload a JPEG instead.";
                        return View(restaurantVm);
                    }

                    if (restaurantVm.Photo.ContentLength > 500 * 1024)
                    {
                        ViewBag.ErrorMessage = "Photo has to be less than 500KB.";
                        return View(restaurantVm);
                    }
                }

                var restaurant = _mappingEngine.Map<Restaurant>(restaurantVm);
                restaurant.Id = id;

                try
                {
                    restaurant = _restaurantService.Update(restaurant);

                    ViewBag.Message = String.Format("Saved '{0}'.", restaurant.Title);
                    ModelState.Clear();
                    restaurantVm = _mappingEngine.Map<Models.RestaurantModel>(restaurant);
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = e.Message;
                }
            }

            return View(restaurantVm);
        }
    }
}

MvcApplication/Views/Restaurant/Edit.cshtml
@using MvcApplication.Models;
@using Business.DomainModel
@using Framework.Extension

@model RestaurantModel
@{
    ViewBag.Title = "Edit";

    var cuisineItems = Enum.GetValues(typeof(CuisineEnum)).Cast<CuisineEnum>()
        .Select(c => new SelectListItem
        {
            Text = c.GetDescription(),
            Value = c.ToString()
        })
        .ToList();
    cuisineItems.Insert(0, new SelectListItem { Text = "Please Select", Value = string.Empty });

    var ratingItems = Enum.GetValues(typeof(RatingEnum)).Cast<RatingEnum>()
        .Select(r => new SelectListItem
        {
            Text = r.GetDescription(),
            Value = ((byte)r).ToString()
        })
        .ToList();
    ratingItems.Insert(0, new SelectListItem { Text = "Please Select", Value = string.Empty });
}

<h2>@Model.Title</h2>

@using (Html.BeginForm("Edit", "Restaurant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Latitude)
    @Html.HiddenFor(x => x.Longitude)
    <table>
        <tr>
            <td>Name</td>
            <td>
                @Html.TextBoxFor(x => x.Title)
                @Html.ValidationMessageFor(m => m.Title)
            </td>
        </tr>
        <tr>
            <td>Phone number</td>
            <td>
                @Html.TextBoxFor(x => x.PhoneNumberText)
                @Html.ValidationMessageFor(m => m.PhoneNumberText)
            </td>
        </tr>
        <tr>
            <td>Cuisine</td>
            <td>@Html.DropDownListFor(x => x.Cuisine, cuisineItems)</td>
        </tr>
        <tr>
            <td>Head chef</td>
            <td>@Html.TextBoxFor(x => x.HeadChefName)</td>
        </tr>
        <tr>
            <td>Food rating</td>
            <td>@Html.DropDownListFor(x => x.RatingFood, ratingItems)</td>
        </tr>
        <tr>
            <td>Wine rating</td>
            <td>@Html.DropDownListFor(x => x.RatingWine, ratingItems)</td>
        </tr>
        <tr>
            <td>Street address</td>
            <td>@Html.TextBoxFor(x => x.StreetAddress)</td>
        </tr>
        <tr>
            <td>Suburb</td>
            <td>@Html.TextBoxFor(x => x.AddressSuburb)</td>
        </tr>
        <tr>
            <td>State</td>
            <td>@Html.TextBoxFor(x => x.AddressState)</td>
        </tr>
        <tr>
            <td>Postcode</td>
            <td>@Html.TextBoxFor(x => x.AddressPostCode)</td>
        </tr>
        <tr>
            <td>Location <br /> <button id="btnLocate">Update Location</button></td>
            <td>
                <div id="locErr" class="message-error"></div>
                <div id="locMap"></div>
            </td>
        </tr>
        <tr>
            <td>Website address</td>
            <td>
                @Html.TextBoxFor(x => x.WebAddress)
                @Html.ValidationMessageFor(m => m.WebAddress)
            </td>
        </tr>
        <tr>
            <td>Review</td>
            <td>@Html.TextAreaFor(x => x.ReviewText)</td>
        </tr>
        <tr>
            <td>Photo<br />(JPG file &lt; 500KB)</td>
            <td><input type="file" name="Photo" id="Photo"/>
                @if (Model.HasPhoto)
                {
                    <br />
                    <img alt="@Model.Title" src="@Url.Action("Photo", new { id = Model.Id })"/>
                }
            </td>
        </tr>        
    </table>

    <input type="submit" value="Save" />
    
    <div class="message-success">@ViewBag.Message</div>
    <div class="message-error">@ViewBag.ErrorMessage</div>
}

@section scripts {
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    @Scripts.Render("~/bundles/cleditor")
    @Scripts.Render("~/bundles/restaurant")
}